build:
  image: golang:1.8
  pull: true
  environment:
    - SHA1=$$COMMIT
    - BUILD_NUMBER=$$BUILD_NUMBER
    - VERSION=0.0.1
  commands:
    - mkdir /drone/bin
    - curl https://glide.sh/get | sh
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr
    - go get github.com/spf13/cobra
    - go get gopkg.in/olivere/elastic.v5
    - gox -output "dist/delete-aws-es-incidents-{{.OS}}-{{.Arch}}" -osarch="linux/amd64 darwin/amd64"
    - ghr -t $$GITHUB_TOKEN -u devops-israel -r delete-aws-es-incidents --replace v$VERSION dist/

publish:
  docker:
    username: $$REGISTRY_USER
    password: $$REGISTRY_PASS
    email: $$REGISTRY_EMAIL
    repo: $$DOCKER_REPO
    tag:
        - "$$BUILD_NUMBER"
        - "latest"
    force_tag: true
    file: Dockerfile
    build_args:
      - version=$VERSION
    when:
      branch: [master]
