build:
  image: golang:1.8
  pull: true
  environment:
    - SHA1=$$COMMIT
    - BUILD_NUMBER=$$BUILD_NUMBER
    - VERSION=$$VERSION
    - GITHUB_TOKEN=$$GITHUB_TOKEN
  commands:
    - mkdir /drone/bin
    - mkdir -p prod
    - mkdir -p dist
    - curl https://glide.sh/get | sh
    - apt-get install build-essentials
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr
    - sed -i "s~delete-aws-es-incidents~github.com/devops-israel/delete-aws-es-incidents~g" main.go
    - glide install
    - glide update
    - gox -output "dist/delete-aws-es-incidents-{{.OS}}-{{.Arch}}" -os="linux darwin windows" -cgo 1 -build-toolchain
    - ghr -t $GITHUB_TOKEN -u devops-israel -r delete-aws-es-incidents --replace v$VERSION dist/
    - cp Dockerfile prod/
    - make build_inside_docker
    - cp delete-aws-es-incidents prod/

publish:
  docker:
    username: $$REGISTRY_USER
    password: $$REGISTRY_PASS
    email: $$REGISTRY_EMAIL
    repo: $$DOCKER_REPO
    tag:
        - "$$BUILD_NUMBER"
        - "latest"
    force_tag: true
    file: prod/Dockerfile
    context: prod/
    when:
      branch: [master]
