workspace:
  base: /go
  path: src/bitbucket.org/joshdvir/delete-aws-es-incidents

pipeline:
  build:
    image: golang:1.8
    pull: true
    commands:
      - pwd
      - mkdir /go/bin
      - mkdir -p prod
      - mkdir -p dist
      - curl https://glide.sh/get | sh
      - go get github.com/mitchellh/gox
      - go get github.com/tcnksm/ghr
      - sed -i "s~delete-aws-es-incidents~github.com/devops-israel/delete-aws-es-incidents~g" main.go
      - glide install
      - glide update
      - gox -osarch-list
      - CGO_ENABLED=0 gox -output "dist/delete-aws-es-incidents-{{.OS}}-{{.Arch}}"
      - ghr -t $GITHUB_TOKEN -u devops-israel -r delete-aws-es-incidents --replace v0.0.${DRONE_BUILD_NUMBER} dist/
      - cp Dockerfile prod/
      - cp dist/delete-aws-es-incidents-linux-amd64 prod/
    secrets: [ github_token ]

  docker:
    image: joshdvir/drone-docker-bash
    repo: joshdvir/delete-aws-es-incidents
    tags:
      - "v0.0.${DRONE_BUILD_NUMBER}"
      - "latest"
    force_tag: true
    keep: 2
    daemon_off: true
    dockerfile: prod/Dockerfile
    context: prod/
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock