FROM golang:1.8

RUN mkdir -p /go/src/delete-aws-es-incidents
WORKDIR /go/src/delete-aws-es-incidents

EXPOSE 9292 2345
RUN curl https://glide.sh/get | sh
RUN go get github.com/derekparker/delve/cmd/dlv

ADD . /go/src/delete-aws-es-incidents
RUN make deps
# RUN make build_inside_docker
CMD ["./delete-aws-es-incidents"]